/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author luiz
 */
public class EasyCut extends javax.swing.JFrame {

    /**
     * Creates new form EasyCut
     */
    public EasyCut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        logLblLogo = new javax.swing.JLabel();
        logLblUsuario = new javax.swing.JLabel();
        logTxtUsuario = new javax.swing.JTextField();
        logLblSenha = new javax.swing.JLabel();
        logPassSenha = new javax.swing.JPasswordField();
        logBttEntrar = new javax.swing.JButton();
        logBttCadastrarSe = new javax.swing.JButton();
        pnlCadastro = new javax.swing.JPanel();
        cadLblLogo = new javax.swing.JLabel();
        cadLblTitulo = new javax.swing.JLabel();
        cadlblNome = new javax.swing.JLabel();
        cadTxtNome = new javax.swing.JTextField();
        cadLblCPF = new javax.swing.JLabel();
        cadTxtCPF = new javax.swing.JTextField();
        cadLblUsuario = new javax.swing.JLabel();
        cadTxtUsuario = new javax.swing.JTextField();
        cadLblSenha = new javax.swing.JLabel();
        cadPassSenha = new javax.swing.JPasswordField();
        cadBttCadastrar = new javax.swing.JButton();
        cadBttEntrar = new javax.swing.JButton();
        pnlCliente = new javax.swing.JPanel();
        cliLblLogo = new javax.swing.JLabel();
        cliLblOla = new javax.swing.JLabel();
        cliSeparador = new javax.swing.JSeparator();
        cliBttReservarHorario = new javax.swing.JButton();
        cliBttExcluirReserva = new javax.swing.JButton();
        cliBttSair = new javax.swing.JButton();
        pnlReservarHorario = new javax.swing.JPanel();
        resLblTitulo = new javax.swing.JLabel();
        resLblServico = new javax.swing.JLabel();
        resBoxServico = new javax.swing.JComboBox<>();
        resLblFuncionario = new javax.swing.JLabel();
        resBoxFuncionario = new javax.swing.JComboBox<>();
        resLblData = new javax.swing.JLabel();
        resChoData = new datechooser.beans.DateChooserCombo();
        resLblHorario = new javax.swing.JLabel();
        resScrHorario = new javax.swing.JScrollPane();
        resLstHorario = new javax.swing.JList<>();
        resBttReservar = new javax.swing.JButton();
        resBttCancelar = new javax.swing.JButton();
        resBttSair = new javax.swing.JButton();
        resLblOla = new javax.swing.JLabel();
        resSeparador = new javax.swing.JSeparator();
        pnlExcluirReserva = new javax.swing.JPanel();
        excLblTitulo = new javax.swing.JLabel();
        excLblOla = new javax.swing.JLabel();
        excBttSair = new javax.swing.JButton();
        excSeparador = new javax.swing.JSeparator();
        excLblReserva = new javax.swing.JLabel();
        excScrReservas = new javax.swing.JScrollPane();
        excTblReservas = new javax.swing.JTable();
        excBttExcluir = new javax.swing.JButton();
        excBttCancelar = new javax.swing.JButton();
        pnlFuncionario = new javax.swing.JPanel();
        funLblTitulo = new javax.swing.JLabel();
        funLblOla = new javax.swing.JLabel();
        funBttSair = new javax.swing.JButton();
        funSeparador = new javax.swing.JSeparator();
        funChoData = new datechooser.beans.DateChooserCombo();
        funLblAgendaDoDia = new javax.swing.JLabel();
        funScrAgenda = new javax.swing.JScrollPane();
        funTblAgenda = new javax.swing.JTable();
        funBttExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyCut");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 600));
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setName("login"); // NOI18N

        logLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logoEasyCut.png"))); // NOI18N

        logLblUsuario.setForeground(new java.awt.Color(102, 0, 153));
        logLblUsuario.setText("Usuário");

        logLblSenha.setForeground(new java.awt.Color(102, 0, 153));
        logLblSenha.setText("Senha");

        logBttEntrar.setBackground(new java.awt.Color(102, 0, 153));
        logBttEntrar.setForeground(new java.awt.Color(255, 255, 255));
        logBttEntrar.setText("Entrar");
        logBttEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBttEntrarActionPerformed(evt);
            }
        });

        logBttCadastrarSe.setBackground(new java.awt.Color(255, 255, 255));
        logBttCadastrarSe.setForeground(new java.awt.Color(102, 0, 153));
        logBttCadastrarSe.setText("Cadastrar-se");
        logBttCadastrarSe.setBorder(null);
        logBttCadastrarSe.setBorderPainted(false);
        logBttCadastrarSe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logBttCadastrarSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBttCadastrarSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(logLblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(logBttEntrar)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logBttCadastrarSe)
                            .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logPassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(logLblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(logTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(logLblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100))))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logLblLogo)
                .addGap(40, 40, 40)
                .addComponent(logLblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logLblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logPassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logBttEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logBttCadastrarSe)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlLogin, "card2");

        pnlCadastro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastro.setName("cadastro"); // NOI18N

        cadLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logoEasyCut.png"))); // NOI18N

        cadLblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        cadLblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cadLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        cadLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadLblTitulo.setText("Cadastro");
        cadLblTitulo.setOpaque(true);

        cadlblNome.setForeground(new java.awt.Color(102, 0, 153));
        cadlblNome.setText("Nome");

        cadLblCPF.setForeground(new java.awt.Color(102, 0, 153));
        cadLblCPF.setText("CPF");

        cadLblUsuario.setForeground(new java.awt.Color(102, 0, 153));
        cadLblUsuario.setText("Usuário");

        cadLblSenha.setForeground(new java.awt.Color(102, 0, 153));
        cadLblSenha.setText("Senha");

        cadBttCadastrar.setBackground(new java.awt.Color(102, 0, 153));
        cadBttCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadBttCadastrar.setText("Cadastrar");
        cadBttCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadBttCadastrarActionPerformed(evt);
            }
        });

        cadBttEntrar.setBackground(new java.awt.Color(255, 255, 255));
        cadBttEntrar.setForeground(new java.awt.Color(102, 0, 153));
        cadBttEntrar.setText("Entrar");
        cadBttEntrar.setBorder(null);
        cadBttEntrar.setBorderPainted(false);
        cadBttEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadBttEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadBttEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadBttEntrar)
                    .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cadLblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadlblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadLblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadLblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadPassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadTxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                .addComponent(cadLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(cadLblLogo))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(cadBttCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cadLblLogo)
                .addGap(18, 18, 18)
                .addComponent(cadLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadlblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadLblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadTxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadLblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadLblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadPassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadBttCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadBttEntrar)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlCadastro, "card3");

        pnlCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlCliente.setName("cliente"); // NOI18N

        cliLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logoEasyCut.png"))); // NOI18N

        cliLblOla.setForeground(new java.awt.Color(102, 0, 153));
        cliLblOla.setText("Olá Usuário!");

        cliSeparador.setBackground(new java.awt.Color(204, 204, 204));
        cliSeparador.setForeground(new java.awt.Color(153, 153, 153));

        cliBttReservarHorario.setBackground(new java.awt.Color(102, 0, 153));
        cliBttReservarHorario.setForeground(new java.awt.Color(255, 255, 255));
        cliBttReservarHorario.setText("Reservar Horário");
        cliBttReservarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliBttReservarHorarioActionPerformed(evt);
            }
        });

        cliBttExcluirReserva.setBackground(new java.awt.Color(102, 0, 153));
        cliBttExcluirReserva.setForeground(new java.awt.Color(255, 255, 255));
        cliBttExcluirReserva.setText("Excluir Reserva");
        cliBttExcluirReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliBttExcluirReservaActionPerformed(evt);
            }
        });

        cliBttSair.setBackground(new java.awt.Color(255, 255, 255));
        cliBttSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cliBttSair.setForeground(new java.awt.Color(102, 0, 153));
        cliBttSair.setText("(sair)");
        cliBttSair.setBorder(null);
        cliBttSair.setBorderPainted(false);
        cliBttSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cliBttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliBttSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(cliLblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cliBttSair, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliBttReservarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliLblOla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliBttExcluirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cliLblLogo)
                .addGap(40, 40, 40)
                .addComponent(cliLblOla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cliSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cliBttReservarHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cliBttExcluirReserva)
                .addGap(18, 18, 18)
                .addComponent(cliBttSair)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlCliente, "card4");

        pnlReservarHorario.setBackground(new java.awt.Color(255, 255, 255));
        pnlReservarHorario.setName("reservar"); // NOI18N

        resLblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        resLblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        resLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resLblTitulo.setText("Reservar Horário");
        resLblTitulo.setOpaque(true);

        resLblServico.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resLblServico.setForeground(new java.awt.Color(102, 0, 153));
        resLblServico.setText("Escolha o serviço:");

        resBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Serviço 1", "Serviço 2", "Serviço 3" }));
        resBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBoxServicoActionPerformed(evt);
            }
        });

        resLblFuncionario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resLblFuncionario.setForeground(new java.awt.Color(102, 0, 153));
        resLblFuncionario.setText("Escolha o funcionário:");
        resLblFuncionario.setEnabled(false);
        resLblFuncionario.setFocusable(false);

        resBoxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Funcionário 1", "Funcionário 2", "Funcionário 3" }));
        resBoxFuncionario.setEnabled(false);
        resBoxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBoxFuncionarioActionPerformed(evt);
            }
        });

        resLblData.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resLblData.setForeground(new java.awt.Color(102, 0, 153));
        resLblData.setText("Escolha a data:");
        resLblData.setEnabled(false);
        resLblData.setFocusable(false);

        resChoData.setEnabled(false);
        resChoData.setLocale(new java.util.Locale("pt", "BR", ""));
        resChoData.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                resChoDataOnSelectionChange(evt);
            }
        });

        resLblHorario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resLblHorario.setForeground(new java.awt.Color(102, 0, 153));
        resLblHorario.setText("Escolha o horário:");
        resLblHorario.setEnabled(false);
        resLblHorario.setFocusable(false);

        resLstHorario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        resLstHorario.setSelectionBackground(new java.awt.Color(102, 0, 153));
        resLstHorario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        resLstHorario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resLstHorarioValueChanged(evt);
            }
        });
        resScrHorario.setViewportView(resLstHorario);

        resBttReservar.setBackground(new java.awt.Color(102, 0, 153));
        resBttReservar.setForeground(new java.awt.Color(255, 255, 255));
        resBttReservar.setText("Reservar");
        resBttReservar.setEnabled(false);
        resBttReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBttReservarActionPerformed(evt);
            }
        });

        resBttCancelar.setBackground(new java.awt.Color(255, 255, 255));
        resBttCancelar.setForeground(new java.awt.Color(102, 0, 153));
        resBttCancelar.setText("Cancelar");
        resBttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBttCancelarActionPerformed(evt);
            }
        });

        resBttSair.setBackground(new java.awt.Color(255, 255, 255));
        resBttSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resBttSair.setForeground(new java.awt.Color(102, 0, 153));
        resBttSair.setText("(sair)");
        resBttSair.setBorder(null);
        resBttSair.setBorderPainted(false);
        resBttSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resBttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBttSairActionPerformed(evt);
            }
        });

        resLblOla.setForeground(new java.awt.Color(102, 0, 153));
        resLblOla.setText("Olá Usuário!");

        resSeparador.setBackground(new java.awt.Color(204, 204, 204));
        resSeparador.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlReservarHorarioLayout = new javax.swing.GroupLayout(pnlReservarHorario);
        pnlReservarHorario.setLayout(pnlReservarHorarioLayout);
        pnlReservarHorarioLayout.setHorizontalGroup(
            pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                .addComponent(resLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                .addGroup(pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                        .addGroup(pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resScrHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resChoData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resBoxServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resLblServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resLblFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resLblData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resLblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resBttCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resBttReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(resSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resLblOla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resBttSair)))
                .addContainerGap())
        );
        pnlReservarHorarioLayout.setVerticalGroup(
            pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservarHorarioLayout.createSequentialGroup()
                .addComponent(resLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReservarHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resLblOla)
                    .addComponent(resBttSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(resLblServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resBoxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resLblFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resLblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resChoData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resLblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resScrHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resBttReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resBttCancelar)
                .addGap(0, 146, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlReservarHorario, "card5");

        pnlExcluirReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlExcluirReserva.setName("excluir"); // NOI18N

        excLblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        excLblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        excLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        excLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        excLblTitulo.setText("Excluir Reservas");
        excLblTitulo.setOpaque(true);

        excLblOla.setForeground(new java.awt.Color(102, 0, 153));
        excLblOla.setText("Olá Usuário!");

        excBttSair.setBackground(new java.awt.Color(255, 255, 255));
        excBttSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        excBttSair.setForeground(new java.awt.Color(102, 0, 153));
        excBttSair.setText("(sair)");
        excBttSair.setBorder(null);
        excBttSair.setBorderPainted(false);
        excBttSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        excBttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excBttSairActionPerformed(evt);
            }
        });

        excSeparador.setBackground(new java.awt.Color(204, 204, 204));
        excSeparador.setForeground(new java.awt.Color(153, 153, 153));

        excLblReserva.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        excLblReserva.setForeground(new java.awt.Color(102, 0, 153));
        excLblReserva.setText("Horários reservados:");

        excTblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,  new Boolean(false)},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Serviço", "Funcionário", "Data", "Hora", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        excTblReservas.getTableHeader().setReorderingAllowed(false);
        excTblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excTblReservasMouseClicked(evt);
            }
        });
        excTblReservas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                excTblReservasKeyPressed(evt);
            }
        });
        excScrReservas.setViewportView(excTblReservas);
        if (excTblReservas.getColumnModel().getColumnCount() > 0) {
            excTblReservas.getColumnModel().getColumn(0).setResizable(false);
            excTblReservas.getColumnModel().getColumn(1).setResizable(false);
            excTblReservas.getColumnModel().getColumn(2).setResizable(false);
            excTblReservas.getColumnModel().getColumn(2).setHeaderValue("Data");
            excTblReservas.getColumnModel().getColumn(3).setResizable(false);
            excTblReservas.getColumnModel().getColumn(4).setResizable(false);
        }

        excBttExcluir.setBackground(new java.awt.Color(102, 0, 153));
        excBttExcluir.setForeground(new java.awt.Color(255, 255, 255));
        excBttExcluir.setText("Excluir");
        excBttExcluir.setEnabled(false);
        excBttExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excBttExcluirActionPerformed(evt);
            }
        });

        excBttCancelar.setBackground(new java.awt.Color(255, 255, 255));
        excBttCancelar.setForeground(new java.awt.Color(102, 0, 153));
        excBttCancelar.setText("Cancelar");
        excBttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excBttCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExcluirReservaLayout = new javax.swing.GroupLayout(pnlExcluirReserva);
        pnlExcluirReserva.setLayout(pnlExcluirReservaLayout);
        pnlExcluirReservaLayout.setHorizontalGroup(
            pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                .addComponent(excLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                .addGroup(pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                                .addComponent(excLblOla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(excBttSair))
                            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                                .addComponent(excSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                        .addGroup(pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(excBttCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(excBttExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(excScrReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(excLblReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExcluirReservaLayout.setVerticalGroup(
            pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExcluirReservaLayout.createSequentialGroup()
                .addComponent(excLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExcluirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excLblOla)
                    .addComponent(excBttSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(excLblReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excScrReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excBttExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excBttCancelar)
                .addGap(0, 205, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlExcluirReserva, "card6");

        pnlFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        pnlFuncionario.setName("funcionario"); // NOI18N

        funLblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        funLblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        funLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        funLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funLblTitulo.setText("Reservas Agendadas");
        funLblTitulo.setOpaque(true);

        funLblOla.setForeground(new java.awt.Color(102, 0, 153));
        funLblOla.setText("Olá Usuário!");

        funBttSair.setBackground(new java.awt.Color(255, 255, 255));
        funBttSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        funBttSair.setForeground(new java.awt.Color(102, 0, 153));
        funBttSair.setText("(sair)");
        funBttSair.setBorder(null);
        funBttSair.setBorderPainted(false);
        funBttSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        funBttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funBttSairActionPerformed(evt);
            }
        });

        funSeparador.setBackground(new java.awt.Color(204, 204, 204));
        funSeparador.setForeground(new java.awt.Color(153, 153, 153));

        funChoData.setLocale(new java.util.Locale("pt", "BR", ""));
        funChoData.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                funChoDataOnSelectionChange(evt);
            }
        });

        funLblAgendaDoDia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        funLblAgendaDoDia.setForeground(new java.awt.Color(102, 0, 153));
        funLblAgendaDoDia.setText("Agenda do dia");

        funTblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null,  new Boolean(false)},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Serviço", "Hora", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        funTblAgenda.getTableHeader().setReorderingAllowed(false);
        funTblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funTblAgendaMouseClicked(evt);
            }
        });
        funTblAgenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                funTblAgendaKeyPressed(evt);
            }
        });
        funScrAgenda.setViewportView(funTblAgenda);
        if (funTblAgenda.getColumnModel().getColumnCount() > 0) {
            funTblAgenda.getColumnModel().getColumn(0).setResizable(false);
            funTblAgenda.getColumnModel().getColumn(1).setResizable(false);
            funTblAgenda.getColumnModel().getColumn(2).setResizable(false);
            funTblAgenda.getColumnModel().getColumn(3).setResizable(false);
        }

        funBttExcluir.setBackground(new java.awt.Color(102, 0, 153));
        funBttExcluir.setForeground(new java.awt.Color(255, 255, 255));
        funBttExcluir.setText("Excluir Horário(s)");
        funBttExcluir.setEnabled(false);
        funBttExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funBttExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFuncionarioLayout = new javax.swing.GroupLayout(pnlFuncionario);
        pnlFuncionario.setLayout(pnlFuncionarioLayout);
        pnlFuncionarioLayout.setHorizontalGroup(
            pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addComponent(funLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(funChoData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                                .addComponent(funLblOla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(funBttSair))
                            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                                .addComponent(funSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(funScrAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(funBttExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(funLblAgendaDoDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFuncionarioLayout.setVerticalGroup(
            pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addComponent(funLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funLblOla)
                    .addComponent(funBttSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(funChoData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(funLblAgendaDoDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funScrAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(funBttExcluir)
                .addGap(0, 200, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlFuncionario, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarTela(javax.swing.JPanel pnl) {
        pnlPrincipal.removeAll();
        pnlPrincipal.add(pnl);
        pnlPrincipal.repaint();
        pnlPrincipal.revalidate();
        
        switch (pnl.getName()) {
            case "login":
                logTxtUsuario.setText("");
                logPassSenha.setText("");
                break;
                
            case "cadastro":
                cadTxtNome.setText("");
                cadTxtCPF.setText("");
                cadTxtUsuario.setText("");
                cadPassSenha.setText("");
                break;
                
                /*
            case "cliente":
                break;
                */
                
            case "reservar":
                // Carregar serviços do banco
                //
                resChoData.setMinDate(resChoData.getDefaultPeriods().getFirstDate());
                resBoxServico.setSelectedIndex(0);
                break;
                
            case "excluir":
                // Carregar reservas do banco
                //
                for (int i = 0; i < excTblReservas.getRowCount(); i++) {
                    excTblReservas.setValueAt(false, i, 4);
                }
                break;
                
            case "funcionario":
                funChoData.setMinDate(funChoData.getDefaultPeriods().getFirstDate());
                funChoData.setSelectedDate(null);
                funLblAgendaDoDia.setText("Selecione uma data");
                break;
        }
    }
    
    private void logBttEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBttEntrarActionPerformed
        // Validar login
        //
        if (!logPassSenha.getText().equals("1")) {
            // Se cliente
            alterarTela(pnlCliente);
            cliLblOla.setText("Olá " + logTxtUsuario.getText());
            resLblOla.setText("Olá " + logTxtUsuario.getText());
            excLblOla.setText("Olá " + logTxtUsuario.getText());
        } else {
            // Se funcionário
            alterarTela(pnlFuncionario);
            funLblOla.setText("Olá " + logTxtUsuario.getText());
        }
    }//GEN-LAST:event_logBttEntrarActionPerformed

    private void logBttCadastrarSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBttCadastrarSeActionPerformed
        alterarTela(pnlCadastro);
    }//GEN-LAST:event_logBttCadastrarSeActionPerformed

    private void cadBttEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadBttEntrarActionPerformed
        alterarTela(pnlLogin);
    }//GEN-LAST:event_cadBttEntrarActionPerformed

    private void cadBttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadBttCadastrarActionPerformed
        // Validar cadastro
        //
        alterarTela(pnlLogin);
        // Informar que o usuário foi cadastrado com sucesso
        //
    }//GEN-LAST:event_cadBttCadastrarActionPerformed

    private void cliBttReservarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliBttReservarHorarioActionPerformed
        alterarTela(pnlReservarHorario);
    }//GEN-LAST:event_cliBttReservarHorarioActionPerformed

    private void cliBttExcluirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliBttExcluirReservaActionPerformed
        alterarTela(pnlExcluirReserva);
    }//GEN-LAST:event_cliBttExcluirReservaActionPerformed

    private void cliBttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliBttSairActionPerformed
        // Deslogar usuário
        //
        alterarTela(pnlLogin);
    }//GEN-LAST:event_cliBttSairActionPerformed

    private void resBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBoxServicoActionPerformed
        resBoxFuncionario.setSelectedIndex(0);
        
        if (resBoxServico.getSelectedIndex() == 0) {
            resBoxFuncionario.setEnabled(false);
            resLblFuncionario.setEnabled(false);
        } else {
            // Carregar funcionários que realizam o serviço selecionado
            //
            resLblFuncionario.setEnabled(true);
            resBoxFuncionario.setEnabled(true);
        }
    }//GEN-LAST:event_resBoxServicoActionPerformed

    private void resBoxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBoxFuncionarioActionPerformed
        resChoData.setSelectedDate(null);
        
        if (resBoxFuncionario.getSelectedIndex() == 0) {
            resChoData.setEnabled(false);
            resLblData.setEnabled(false);
        } else {
            resLblData.setEnabled(true);
            resChoData.setEnabled(true);
        }
    }//GEN-LAST:event_resBoxFuncionarioActionPerformed

    private void resChoDataOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_resChoDataOnSelectionChange
        resLstHorario.setSelectedIndex(0);
        
        if (resChoData.getSelectedDate() == null) {
            resLstHorario.setVisible(false);
        } else {
            // Carregar horários vagos do funcinário na data selecionada
            //
            resLstHorario.setVisible(true);
        }
    }//GEN-LAST:event_resChoDataOnSelectionChange

    private void resLstHorarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resLstHorarioValueChanged
        if (resLstHorario.getSelectedIndex() == 0) {
            resBttReservar.setEnabled(false);
        } else {
            resBttReservar.setEnabled(true);
        }
    }//GEN-LAST:event_resLstHorarioValueChanged

    private void resBttReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBttReservarActionPerformed
        // Registrar reserva
        //
        alterarTela(pnlCliente);
        // Informar que serviço foi confirmado
    }//GEN-LAST:event_resBttReservarActionPerformed

    private void resBttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBttCancelarActionPerformed
        alterarTela(pnlCliente);
    }//GEN-LAST:event_resBttCancelarActionPerformed

    private void resBttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBttSairActionPerformed
        // Deslogar usuário
        //
        alterarTela(pnlLogin);
    }//GEN-LAST:event_resBttSairActionPerformed

    private void excBttExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excBttExcluirActionPerformed
        // Excluir reserva(s) selecionada(s)
        //
        alterarTela(pnlCliente);
        // Informar que a(s) reserva(s) foi(ram) excluída(s) com sucesso
    }//GEN-LAST:event_excBttExcluirActionPerformed

    private void excBttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excBttCancelarActionPerformed
        alterarTela(pnlCliente);
    }//GEN-LAST:event_excBttCancelarActionPerformed

    private void excBttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excBttSairActionPerformed
        // Deslogar usuário
        //
        alterarTela(pnlLogin);
    }//GEN-LAST:event_excBttSairActionPerformed

    private void excTblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excTblReservasMouseClicked
        boolean reserva = false;
        
        for (int i = 0; i < excTblReservas.getRowCount(); i++) {
            if (excTblReservas.getValueAt(i, 4).equals(true)) {
                reserva = true;
            }
        }
        excBttExcluir.setEnabled(reserva);
    }//GEN-LAST:event_excTblReservasMouseClicked

    private void excTblReservasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_excTblReservasKeyPressed
        boolean reserva = false;
        
        for (int i = 0; i < excTblReservas.getRowCount(); i++) {
            if (excTblReservas.getValueAt(i, 4).equals(true)) {
                reserva = true;
            }
        }
        excBttExcluir.setEnabled(reserva);
    }//GEN-LAST:event_excTblReservasKeyPressed

    private void funBttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funBttSairActionPerformed
        // Deslogar usuário
        //
        alterarTela(pnlLogin);
    }//GEN-LAST:event_funBttSairActionPerformed

    private void funTblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funTblAgendaMouseClicked
        boolean reserva = false;
        
        for (int i = 0; i < funTblAgenda.getRowCount(); i++) {
            if (funTblAgenda.getValueAt(i, 3).equals(true)) {
                reserva = true;
            }
        }
        funBttExcluir.setEnabled(reserva);
    }//GEN-LAST:event_funTblAgendaMouseClicked

    private void funTblAgendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_funTblAgendaKeyPressed
        boolean reserva = false;
        
        for (int i = 0; i < funTblAgenda.getRowCount(); i++) {
            if (funTblAgenda.getValueAt(i, 3).equals(true)) {
                reserva = true;
            }
        }
        funBttExcluir.setEnabled(reserva);
    }//GEN-LAST:event_funTblAgendaKeyPressed

    private void funBttExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funBttExcluirActionPerformed
        // Excluir reserva(s) selecionada(s)
        //
        // Informar que a(s) reserva(s) foi(ram) excluída(s) com sucesso
        //
        alterarTela(pnlFuncionario);
    }//GEN-LAST:event_funBttExcluirActionPerformed

    private void funChoDataOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_funChoDataOnSelectionChange
        funBttExcluir.setEnabled(false);
        
        if (funChoData.getSelectedDate() == null) {
            funLblAgendaDoDia.setText("Selecione uma data");
            funTblAgenda.setVisible(false);
        } else {
            SimpleDateFormat data = new SimpleDateFormat("dd/MM");
            funLblAgendaDoDia.setText("Reservas agendadas para o dia " + data.format(funChoData.getSelectedDate().getTime()));
            
            // Carregar horários reservados do funcinário na data selecionada
            //
            
            funTblAgenda.setVisible(true);
        }
        
        for (int i = 0; i < funTblAgenda.getRowCount(); i++) {
            funTblAgenda.setValueAt(false, i, 3);
        }
    }//GEN-LAST:event_funChoDataOnSelectionChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyCut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyCut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyCut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyCut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyCut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadBttCadastrar;
    private javax.swing.JButton cadBttEntrar;
    private javax.swing.JLabel cadLblCPF;
    private javax.swing.JLabel cadLblLogo;
    private javax.swing.JLabel cadLblSenha;
    private javax.swing.JLabel cadLblTitulo;
    private javax.swing.JLabel cadLblUsuario;
    private javax.swing.JPasswordField cadPassSenha;
    private javax.swing.JTextField cadTxtCPF;
    private javax.swing.JTextField cadTxtNome;
    private javax.swing.JTextField cadTxtUsuario;
    private javax.swing.JLabel cadlblNome;
    private javax.swing.JButton cliBttExcluirReserva;
    private javax.swing.JButton cliBttReservarHorario;
    private javax.swing.JButton cliBttSair;
    private javax.swing.JLabel cliLblLogo;
    private javax.swing.JLabel cliLblOla;
    private javax.swing.JSeparator cliSeparador;
    private javax.swing.JButton excBttCancelar;
    private javax.swing.JButton excBttExcluir;
    private javax.swing.JButton excBttSair;
    private javax.swing.JLabel excLblOla;
    private javax.swing.JLabel excLblReserva;
    private javax.swing.JLabel excLblTitulo;
    private javax.swing.JScrollPane excScrReservas;
    private javax.swing.JSeparator excSeparador;
    private javax.swing.JTable excTblReservas;
    private javax.swing.JButton funBttExcluir;
    private javax.swing.JButton funBttSair;
    private datechooser.beans.DateChooserCombo funChoData;
    private javax.swing.JLabel funLblAgendaDoDia;
    private javax.swing.JLabel funLblOla;
    private javax.swing.JLabel funLblTitulo;
    private javax.swing.JScrollPane funScrAgenda;
    private javax.swing.JSeparator funSeparador;
    private javax.swing.JTable funTblAgenda;
    private javax.swing.JButton logBttCadastrarSe;
    private javax.swing.JButton logBttEntrar;
    private javax.swing.JLabel logLblLogo;
    private javax.swing.JLabel logLblSenha;
    private javax.swing.JLabel logLblUsuario;
    private javax.swing.JPasswordField logPassSenha;
    private javax.swing.JTextField logTxtUsuario;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlExcluirReserva;
    private javax.swing.JPanel pnlFuncionario;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlReservarHorario;
    private javax.swing.JComboBox<String> resBoxFuncionario;
    private javax.swing.JComboBox<String> resBoxServico;
    private javax.swing.JButton resBttCancelar;
    private javax.swing.JButton resBttReservar;
    private javax.swing.JButton resBttSair;
    private datechooser.beans.DateChooserCombo resChoData;
    private javax.swing.JLabel resLblData;
    private javax.swing.JLabel resLblFuncionario;
    private javax.swing.JLabel resLblHorario;
    private javax.swing.JLabel resLblOla;
    private javax.swing.JLabel resLblServico;
    private javax.swing.JLabel resLblTitulo;
    private javax.swing.JList<String> resLstHorario;
    private javax.swing.JScrollPane resScrHorario;
    private javax.swing.JSeparator resSeparador;
    // End of variables declaration//GEN-END:variables
}
